/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin.index'
import { Route as SuperAdminUsersRouteImport } from './routes/super-admin.users'
import { Route as SuperAdminSettingsRouteImport } from './routes/super-admin.settings'
import { Route as SuperAdminPlansRouteImport } from './routes/super-admin.plans'
import { Route as SuperAdminOrganizationsRouteImport } from './routes/super-admin.organizations'
import { Route as SuperAdminModulesRouteImport } from './routes/super-admin.modules'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as ESlugRouteImport } from './routes/e.$slug'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPublicLinksRouteImport } from './routes/admin.public-links'
import { Route as AdminPrintQueueRouteImport } from './routes/admin.print-queue'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminOnlineOrdersRouteImport } from './routes/admin.online-orders'
import { Route as AdminOnlineMenuRouteImport } from './routes/admin.online-menu'
import { Route as AdminNfcCardsRouteImport } from './routes/admin.nfc-cards'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as AdminDevicesRouteImport } from './routes/admin.devices'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'
import { Route as AdminActivitiesRouteImport } from './routes/admin.activities'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin.settings.index'
import { Route as AdminEventsIndexRouteImport } from './routes/admin.events.index'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin.customers.index'
import { Route as ChamadaLojaSlugRouteImport } from './routes/chamada.loja.$slug'
import { Route as ChamadaEventoSlugRouteImport } from './routes/chamada.evento.$slug'
import { Route as AdminSettingsPrintingRouteImport } from './routes/admin.settings.printing'
import { Route as AdminSettingsPaymentsRouteImport } from './routes/admin.settings.payments'
import { Route as AdminSettingsOrganizationRouteImport } from './routes/admin.settings.organization'
import { Route as AdminSettingsOnlineOrdersRouteImport } from './routes/admin.settings.online-orders'
import { Route as AdminSettingsLegacyRouteImport } from './routes/admin.settings.legacy'
import { Route as AdminSettingsDeliveryRouteImport } from './routes/admin.settings.delivery'
import { Route as AdminSettingsCheckoutRouteImport } from './routes/admin.settings.checkout'
import { Route as AdminSettingsCatalogOnlineRouteImport } from './routes/admin.settings.catalog-online'
import { Route as AdminSettingsBusinessHoursRouteImport } from './routes/admin.settings.business-hours'
import { Route as AdminSettingsBrandingRouteImport } from './routes/admin.settings.branding'
import { Route as AdminEventsIdRouteImport } from './routes/admin.events.$id'
import { Route as AdminDevicesIdRouteImport } from './routes/admin.devices.$id'
import { Route as AdminCustomersIdRouteImport } from './routes/admin.customers.$id'
import { Route as AdminSettingsDeliveryRulesRouteImport } from './routes/admin.settings.delivery.rules'
import { Route as AdminEventsIdPrintingRouteImport } from './routes/admin.events.$id.printing'
import { Route as AdminEventsIdPaymentsRouteImport } from './routes/admin.events.$id.payments'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminUsersRoute = SuperAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminSettingsRoute = SuperAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminPlansRoute = SuperAdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminOrganizationsRoute = SuperAdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminModulesRoute = SuperAdminModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => SuperAdminRoute,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ESlugRoute = ESlugRouteImport.update({
  id: '/e/$slug',
  path: '/e/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPublicLinksRoute = AdminPublicLinksRouteImport.update({
  id: '/public-links',
  path: '/public-links',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPrintQueueRoute = AdminPrintQueueRouteImport.update({
  id: '/print-queue',
  path: '/print-queue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOnlineOrdersRoute = AdminOnlineOrdersRouteImport.update({
  id: '/online-orders',
  path: '/online-orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOnlineMenuRoute = AdminOnlineMenuRouteImport.update({
  id: '/online-menu',
  path: '/online-menu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNfcCardsRoute = AdminNfcCardsRouteImport.update({
  id: '/nfc-cards',
  path: '/nfc-cards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDevicesRoute = AdminDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivitiesRoute = AdminActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AdminRoute,
} as any)
const ChamadaLojaSlugRoute = ChamadaLojaSlugRouteImport.update({
  id: '/chamada/loja/$slug',
  path: '/chamada/loja/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamadaEventoSlugRoute = ChamadaEventoSlugRouteImport.update({
  id: '/chamada/evento/$slug',
  path: '/chamada/evento/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsPrintingRoute = AdminSettingsPrintingRouteImport.update({
  id: '/printing',
  path: '/printing',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsPaymentsRoute = AdminSettingsPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsOrganizationRoute =
  AdminSettingsOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => AdminSettingsRoute,
  } as any)
const AdminSettingsOnlineOrdersRoute =
  AdminSettingsOnlineOrdersRouteImport.update({
    id: '/online-orders',
    path: '/online-orders',
    getParentRoute: () => AdminSettingsRoute,
  } as any)
const AdminSettingsLegacyRoute = AdminSettingsLegacyRouteImport.update({
  id: '/legacy',
  path: '/legacy',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsDeliveryRoute = AdminSettingsDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsCheckoutRoute = AdminSettingsCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsCatalogOnlineRoute =
  AdminSettingsCatalogOnlineRouteImport.update({
    id: '/catalog-online',
    path: '/catalog-online',
    getParentRoute: () => AdminSettingsRoute,
  } as any)
const AdminSettingsBusinessHoursRoute =
  AdminSettingsBusinessHoursRouteImport.update({
    id: '/business-hours',
    path: '/business-hours',
    getParentRoute: () => AdminSettingsRoute,
  } as any)
const AdminSettingsBrandingRoute = AdminSettingsBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminEventsIdRoute = AdminEventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDevicesIdRoute = AdminDevicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminDevicesRoute,
} as any)
const AdminCustomersIdRoute = AdminCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsDeliveryRulesRoute =
  AdminSettingsDeliveryRulesRouteImport.update({
    id: '/rules',
    path: '/rules',
    getParentRoute: () => AdminSettingsDeliveryRoute,
  } as any)
const AdminEventsIdPrintingRoute = AdminEventsIdPrintingRouteImport.update({
  id: '/printing',
  path: '/printing',
  getParentRoute: () => AdminEventsIdRoute,
} as any)
const AdminEventsIdPaymentsRoute = AdminEventsIdPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminEventsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/devices': typeof AdminDevicesRouteWithChildren
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/nfc-cards': typeof AdminNfcCardsRoute
  '/admin/online-menu': typeof AdminOnlineMenuRoute
  '/admin/online-orders': typeof AdminOnlineOrdersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/print-queue': typeof AdminPrintQueueRoute
  '/admin/public-links': typeof AdminPublicLinksRoute
  '/admin/settings': typeof AdminSettingsRouteWithChildren
  '/e/$slug': typeof ESlugRoute
  '/p/$slug': typeof PSlugRoute
  '/super-admin/modules': typeof SuperAdminModulesRoute
  '/super-admin/organizations': typeof SuperAdminOrganizationsRoute
  '/super-admin/plans': typeof SuperAdminPlansRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/devices/$id': typeof AdminDevicesIdRoute
  '/admin/events/$id': typeof AdminEventsIdRouteWithChildren
  '/admin/settings/branding': typeof AdminSettingsBrandingRoute
  '/admin/settings/business-hours': typeof AdminSettingsBusinessHoursRoute
  '/admin/settings/catalog-online': typeof AdminSettingsCatalogOnlineRoute
  '/admin/settings/checkout': typeof AdminSettingsCheckoutRoute
  '/admin/settings/delivery': typeof AdminSettingsDeliveryRouteWithChildren
  '/admin/settings/legacy': typeof AdminSettingsLegacyRoute
  '/admin/settings/online-orders': typeof AdminSettingsOnlineOrdersRoute
  '/admin/settings/organization': typeof AdminSettingsOrganizationRoute
  '/admin/settings/payments': typeof AdminSettingsPaymentsRoute
  '/admin/settings/printing': typeof AdminSettingsPrintingRoute
  '/chamada/evento/$slug': typeof ChamadaEventoSlugRoute
  '/chamada/loja/$slug': typeof ChamadaLojaSlugRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/events/$id/payments': typeof AdminEventsIdPaymentsRoute
  '/admin/events/$id/printing': typeof AdminEventsIdPrintingRoute
  '/admin/settings/delivery/rules': typeof AdminSettingsDeliveryRulesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/devices': typeof AdminDevicesRouteWithChildren
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/nfc-cards': typeof AdminNfcCardsRoute
  '/admin/online-menu': typeof AdminOnlineMenuRoute
  '/admin/online-orders': typeof AdminOnlineOrdersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/print-queue': typeof AdminPrintQueueRoute
  '/admin/public-links': typeof AdminPublicLinksRoute
  '/e/$slug': typeof ESlugRoute
  '/p/$slug': typeof PSlugRoute
  '/super-admin/modules': typeof SuperAdminModulesRoute
  '/super-admin/organizations': typeof SuperAdminOrganizationsRoute
  '/super-admin/plans': typeof SuperAdminPlansRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/super-admin': typeof SuperAdminIndexRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/devices/$id': typeof AdminDevicesIdRoute
  '/admin/events/$id': typeof AdminEventsIdRouteWithChildren
  '/admin/settings/branding': typeof AdminSettingsBrandingRoute
  '/admin/settings/business-hours': typeof AdminSettingsBusinessHoursRoute
  '/admin/settings/catalog-online': typeof AdminSettingsCatalogOnlineRoute
  '/admin/settings/checkout': typeof AdminSettingsCheckoutRoute
  '/admin/settings/delivery': typeof AdminSettingsDeliveryRouteWithChildren
  '/admin/settings/legacy': typeof AdminSettingsLegacyRoute
  '/admin/settings/online-orders': typeof AdminSettingsOnlineOrdersRoute
  '/admin/settings/organization': typeof AdminSettingsOrganizationRoute
  '/admin/settings/payments': typeof AdminSettingsPaymentsRoute
  '/admin/settings/printing': typeof AdminSettingsPrintingRoute
  '/chamada/evento/$slug': typeof ChamadaEventoSlugRoute
  '/chamada/loja/$slug': typeof ChamadaLojaSlugRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/events/$id/payments': typeof AdminEventsIdPaymentsRoute
  '/admin/events/$id/printing': typeof AdminEventsIdPrintingRoute
  '/admin/settings/delivery/rules': typeof AdminSettingsDeliveryRulesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/devices': typeof AdminDevicesRouteWithChildren
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/nfc-cards': typeof AdminNfcCardsRoute
  '/admin/online-menu': typeof AdminOnlineMenuRoute
  '/admin/online-orders': typeof AdminOnlineOrdersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/print-queue': typeof AdminPrintQueueRoute
  '/admin/public-links': typeof AdminPublicLinksRoute
  '/admin/settings': typeof AdminSettingsRouteWithChildren
  '/e/$slug': typeof ESlugRoute
  '/p/$slug': typeof PSlugRoute
  '/super-admin/modules': typeof SuperAdminModulesRoute
  '/super-admin/organizations': typeof SuperAdminOrganizationsRoute
  '/super-admin/plans': typeof SuperAdminPlansRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/devices/$id': typeof AdminDevicesIdRoute
  '/admin/events/$id': typeof AdminEventsIdRouteWithChildren
  '/admin/settings/branding': typeof AdminSettingsBrandingRoute
  '/admin/settings/business-hours': typeof AdminSettingsBusinessHoursRoute
  '/admin/settings/catalog-online': typeof AdminSettingsCatalogOnlineRoute
  '/admin/settings/checkout': typeof AdminSettingsCheckoutRoute
  '/admin/settings/delivery': typeof AdminSettingsDeliveryRouteWithChildren
  '/admin/settings/legacy': typeof AdminSettingsLegacyRoute
  '/admin/settings/online-orders': typeof AdminSettingsOnlineOrdersRoute
  '/admin/settings/organization': typeof AdminSettingsOrganizationRoute
  '/admin/settings/payments': typeof AdminSettingsPaymentsRoute
  '/admin/settings/printing': typeof AdminSettingsPrintingRoute
  '/chamada/evento/$slug': typeof ChamadaEventoSlugRoute
  '/chamada/loja/$slug': typeof ChamadaLojaSlugRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/events/$id/payments': typeof AdminEventsIdPaymentsRoute
  '/admin/events/$id/printing': typeof AdminEventsIdPrintingRoute
  '/admin/settings/delivery/rules': typeof AdminSettingsDeliveryRulesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/super-admin'
    | '/unauthorized'
    | '/admin/activities'
    | '/admin/catalog'
    | '/admin/dashboard'
    | '/admin/devices'
    | '/admin/financeiro'
    | '/admin/login'
    | '/admin/nfc-cards'
    | '/admin/online-menu'
    | '/admin/online-orders'
    | '/admin/orders'
    | '/admin/print-queue'
    | '/admin/public-links'
    | '/admin/settings'
    | '/e/$slug'
    | '/p/$slug'
    | '/super-admin/modules'
    | '/super-admin/organizations'
    | '/super-admin/plans'
    | '/super-admin/settings'
    | '/super-admin/users'
    | '/super-admin/'
    | '/admin/customers/$id'
    | '/admin/devices/$id'
    | '/admin/events/$id'
    | '/admin/settings/branding'
    | '/admin/settings/business-hours'
    | '/admin/settings/catalog-online'
    | '/admin/settings/checkout'
    | '/admin/settings/delivery'
    | '/admin/settings/legacy'
    | '/admin/settings/online-orders'
    | '/admin/settings/organization'
    | '/admin/settings/payments'
    | '/admin/settings/printing'
    | '/chamada/evento/$slug'
    | '/chamada/loja/$slug'
    | '/admin/customers/'
    | '/admin/events/'
    | '/admin/settings/'
    | '/admin/events/$id/payments'
    | '/admin/events/$id/printing'
    | '/admin/settings/delivery/rules'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/unauthorized'
    | '/admin/activities'
    | '/admin/catalog'
    | '/admin/dashboard'
    | '/admin/devices'
    | '/admin/financeiro'
    | '/admin/login'
    | '/admin/nfc-cards'
    | '/admin/online-menu'
    | '/admin/online-orders'
    | '/admin/orders'
    | '/admin/print-queue'
    | '/admin/public-links'
    | '/e/$slug'
    | '/p/$slug'
    | '/super-admin/modules'
    | '/super-admin/organizations'
    | '/super-admin/plans'
    | '/super-admin/settings'
    | '/super-admin/users'
    | '/super-admin'
    | '/admin/customers/$id'
    | '/admin/devices/$id'
    | '/admin/events/$id'
    | '/admin/settings/branding'
    | '/admin/settings/business-hours'
    | '/admin/settings/catalog-online'
    | '/admin/settings/checkout'
    | '/admin/settings/delivery'
    | '/admin/settings/legacy'
    | '/admin/settings/online-orders'
    | '/admin/settings/organization'
    | '/admin/settings/payments'
    | '/admin/settings/printing'
    | '/chamada/evento/$slug'
    | '/chamada/loja/$slug'
    | '/admin/customers'
    | '/admin/events'
    | '/admin/settings'
    | '/admin/events/$id/payments'
    | '/admin/events/$id/printing'
    | '/admin/settings/delivery/rules'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/super-admin'
    | '/unauthorized'
    | '/admin/activities'
    | '/admin/catalog'
    | '/admin/dashboard'
    | '/admin/devices'
    | '/admin/financeiro'
    | '/admin/login'
    | '/admin/nfc-cards'
    | '/admin/online-menu'
    | '/admin/online-orders'
    | '/admin/orders'
    | '/admin/print-queue'
    | '/admin/public-links'
    | '/admin/settings'
    | '/e/$slug'
    | '/p/$slug'
    | '/super-admin/modules'
    | '/super-admin/organizations'
    | '/super-admin/plans'
    | '/super-admin/settings'
    | '/super-admin/users'
    | '/super-admin/'
    | '/admin/customers/$id'
    | '/admin/devices/$id'
    | '/admin/events/$id'
    | '/admin/settings/branding'
    | '/admin/settings/business-hours'
    | '/admin/settings/catalog-online'
    | '/admin/settings/checkout'
    | '/admin/settings/delivery'
    | '/admin/settings/legacy'
    | '/admin/settings/online-orders'
    | '/admin/settings/organization'
    | '/admin/settings/payments'
    | '/admin/settings/printing'
    | '/chamada/evento/$slug'
    | '/chamada/loja/$slug'
    | '/admin/customers/'
    | '/admin/events/'
    | '/admin/settings/'
    | '/admin/events/$id/payments'
    | '/admin/events/$id/printing'
    | '/admin/settings/delivery/rules'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRoute
  ESlugRoute: typeof ESlugRoute
  PSlugRoute: typeof PSlugRoute
  ChamadaEventoSlugRoute: typeof ChamadaEventoSlugRoute
  ChamadaLojaSlugRoute: typeof ChamadaLojaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/users': {
      id: '/super-admin/users'
      path: '/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof SuperAdminUsersRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/settings': {
      id: '/super-admin/settings'
      path: '/settings'
      fullPath: '/super-admin/settings'
      preLoaderRoute: typeof SuperAdminSettingsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/plans': {
      id: '/super-admin/plans'
      path: '/plans'
      fullPath: '/super-admin/plans'
      preLoaderRoute: typeof SuperAdminPlansRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/organizations': {
      id: '/super-admin/organizations'
      path: '/organizations'
      fullPath: '/super-admin/organizations'
      preLoaderRoute: typeof SuperAdminOrganizationsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/modules': {
      id: '/super-admin/modules'
      path: '/modules'
      fullPath: '/super-admin/modules'
      preLoaderRoute: typeof SuperAdminModulesRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$slug': {
      id: '/e/$slug'
      path: '/e/$slug'
      fullPath: '/e/$slug'
      preLoaderRoute: typeof ESlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/public-links': {
      id: '/admin/public-links'
      path: '/public-links'
      fullPath: '/admin/public-links'
      preLoaderRoute: typeof AdminPublicLinksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/print-queue': {
      id: '/admin/print-queue'
      path: '/print-queue'
      fullPath: '/admin/print-queue'
      preLoaderRoute: typeof AdminPrintQueueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/online-orders': {
      id: '/admin/online-orders'
      path: '/online-orders'
      fullPath: '/admin/online-orders'
      preLoaderRoute: typeof AdminOnlineOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/online-menu': {
      id: '/admin/online-menu'
      path: '/online-menu'
      fullPath: '/admin/online-menu'
      preLoaderRoute: typeof AdminOnlineMenuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/nfc-cards': {
      id: '/admin/nfc-cards'
      path: '/nfc-cards'
      fullPath: '/admin/nfc-cards'
      preLoaderRoute: typeof AdminNfcCardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/devices': {
      id: '/admin/devices'
      path: '/devices'
      fullPath: '/admin/devices'
      preLoaderRoute: typeof AdminDevicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activities': {
      id: '/admin/activities'
      path: '/activities'
      fullPath: '/admin/activities'
      preLoaderRoute: typeof AdminActivitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/chamada/loja/$slug': {
      id: '/chamada/loja/$slug'
      path: '/chamada/loja/$slug'
      fullPath: '/chamada/loja/$slug'
      preLoaderRoute: typeof ChamadaLojaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamada/evento/$slug': {
      id: '/chamada/evento/$slug'
      path: '/chamada/evento/$slug'
      fullPath: '/chamada/evento/$slug'
      preLoaderRoute: typeof ChamadaEventoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/printing': {
      id: '/admin/settings/printing'
      path: '/printing'
      fullPath: '/admin/settings/printing'
      preLoaderRoute: typeof AdminSettingsPrintingRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/payments': {
      id: '/admin/settings/payments'
      path: '/payments'
      fullPath: '/admin/settings/payments'
      preLoaderRoute: typeof AdminSettingsPaymentsRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/organization': {
      id: '/admin/settings/organization'
      path: '/organization'
      fullPath: '/admin/settings/organization'
      preLoaderRoute: typeof AdminSettingsOrganizationRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/online-orders': {
      id: '/admin/settings/online-orders'
      path: '/online-orders'
      fullPath: '/admin/settings/online-orders'
      preLoaderRoute: typeof AdminSettingsOnlineOrdersRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/legacy': {
      id: '/admin/settings/legacy'
      path: '/legacy'
      fullPath: '/admin/settings/legacy'
      preLoaderRoute: typeof AdminSettingsLegacyRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/delivery': {
      id: '/admin/settings/delivery'
      path: '/delivery'
      fullPath: '/admin/settings/delivery'
      preLoaderRoute: typeof AdminSettingsDeliveryRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/checkout': {
      id: '/admin/settings/checkout'
      path: '/checkout'
      fullPath: '/admin/settings/checkout'
      preLoaderRoute: typeof AdminSettingsCheckoutRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/catalog-online': {
      id: '/admin/settings/catalog-online'
      path: '/catalog-online'
      fullPath: '/admin/settings/catalog-online'
      preLoaderRoute: typeof AdminSettingsCatalogOnlineRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/business-hours': {
      id: '/admin/settings/business-hours'
      path: '/business-hours'
      fullPath: '/admin/settings/business-hours'
      preLoaderRoute: typeof AdminSettingsBusinessHoursRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/branding': {
      id: '/admin/settings/branding'
      path: '/branding'
      fullPath: '/admin/settings/branding'
      preLoaderRoute: typeof AdminSettingsBrandingRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/events/$id': {
      id: '/admin/events/$id'
      path: '/events/$id'
      fullPath: '/admin/events/$id'
      preLoaderRoute: typeof AdminEventsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/devices/$id': {
      id: '/admin/devices/$id'
      path: '/$id'
      fullPath: '/admin/devices/$id'
      preLoaderRoute: typeof AdminDevicesIdRouteImport
      parentRoute: typeof AdminDevicesRoute
    }
    '/admin/customers/$id': {
      id: '/admin/customers/$id'
      path: '/customers/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AdminCustomersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/delivery/rules': {
      id: '/admin/settings/delivery/rules'
      path: '/rules'
      fullPath: '/admin/settings/delivery/rules'
      preLoaderRoute: typeof AdminSettingsDeliveryRulesRouteImport
      parentRoute: typeof AdminSettingsDeliveryRoute
    }
    '/admin/events/$id/printing': {
      id: '/admin/events/$id/printing'
      path: '/printing'
      fullPath: '/admin/events/$id/printing'
      preLoaderRoute: typeof AdminEventsIdPrintingRouteImport
      parentRoute: typeof AdminEventsIdRoute
    }
    '/admin/events/$id/payments': {
      id: '/admin/events/$id/payments'
      path: '/payments'
      fullPath: '/admin/events/$id/payments'
      preLoaderRoute: typeof AdminEventsIdPaymentsRouteImport
      parentRoute: typeof AdminEventsIdRoute
    }
  }
}

interface AdminDevicesRouteChildren {
  AdminDevicesIdRoute: typeof AdminDevicesIdRoute
}

const AdminDevicesRouteChildren: AdminDevicesRouteChildren = {
  AdminDevicesIdRoute: AdminDevicesIdRoute,
}

const AdminDevicesRouteWithChildren = AdminDevicesRoute._addFileChildren(
  AdminDevicesRouteChildren,
)

interface AdminSettingsDeliveryRouteChildren {
  AdminSettingsDeliveryRulesRoute: typeof AdminSettingsDeliveryRulesRoute
}

const AdminSettingsDeliveryRouteChildren: AdminSettingsDeliveryRouteChildren = {
  AdminSettingsDeliveryRulesRoute: AdminSettingsDeliveryRulesRoute,
}

const AdminSettingsDeliveryRouteWithChildren =
  AdminSettingsDeliveryRoute._addFileChildren(
    AdminSettingsDeliveryRouteChildren,
  )

interface AdminSettingsRouteChildren {
  AdminSettingsBrandingRoute: typeof AdminSettingsBrandingRoute
  AdminSettingsBusinessHoursRoute: typeof AdminSettingsBusinessHoursRoute
  AdminSettingsCatalogOnlineRoute: typeof AdminSettingsCatalogOnlineRoute
  AdminSettingsCheckoutRoute: typeof AdminSettingsCheckoutRoute
  AdminSettingsDeliveryRoute: typeof AdminSettingsDeliveryRouteWithChildren
  AdminSettingsLegacyRoute: typeof AdminSettingsLegacyRoute
  AdminSettingsOnlineOrdersRoute: typeof AdminSettingsOnlineOrdersRoute
  AdminSettingsOrganizationRoute: typeof AdminSettingsOrganizationRoute
  AdminSettingsPaymentsRoute: typeof AdminSettingsPaymentsRoute
  AdminSettingsPrintingRoute: typeof AdminSettingsPrintingRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
}

const AdminSettingsRouteChildren: AdminSettingsRouteChildren = {
  AdminSettingsBrandingRoute: AdminSettingsBrandingRoute,
  AdminSettingsBusinessHoursRoute: AdminSettingsBusinessHoursRoute,
  AdminSettingsCatalogOnlineRoute: AdminSettingsCatalogOnlineRoute,
  AdminSettingsCheckoutRoute: AdminSettingsCheckoutRoute,
  AdminSettingsDeliveryRoute: AdminSettingsDeliveryRouteWithChildren,
  AdminSettingsLegacyRoute: AdminSettingsLegacyRoute,
  AdminSettingsOnlineOrdersRoute: AdminSettingsOnlineOrdersRoute,
  AdminSettingsOrganizationRoute: AdminSettingsOrganizationRoute,
  AdminSettingsPaymentsRoute: AdminSettingsPaymentsRoute,
  AdminSettingsPrintingRoute: AdminSettingsPrintingRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
}

const AdminSettingsRouteWithChildren = AdminSettingsRoute._addFileChildren(
  AdminSettingsRouteChildren,
)

interface AdminEventsIdRouteChildren {
  AdminEventsIdPaymentsRoute: typeof AdminEventsIdPaymentsRoute
  AdminEventsIdPrintingRoute: typeof AdminEventsIdPrintingRoute
}

const AdminEventsIdRouteChildren: AdminEventsIdRouteChildren = {
  AdminEventsIdPaymentsRoute: AdminEventsIdPaymentsRoute,
  AdminEventsIdPrintingRoute: AdminEventsIdPrintingRoute,
}

const AdminEventsIdRouteWithChildren = AdminEventsIdRoute._addFileChildren(
  AdminEventsIdRouteChildren,
)

interface AdminRouteChildren {
  AdminActivitiesRoute: typeof AdminActivitiesRoute
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDevicesRoute: typeof AdminDevicesRouteWithChildren
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNfcCardsRoute: typeof AdminNfcCardsRoute
  AdminOnlineMenuRoute: typeof AdminOnlineMenuRoute
  AdminOnlineOrdersRoute: typeof AdminOnlineOrdersRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPrintQueueRoute: typeof AdminPrintQueueRoute
  AdminPublicLinksRoute: typeof AdminPublicLinksRoute
  AdminSettingsRoute: typeof AdminSettingsRouteWithChildren
  AdminCustomersIdRoute: typeof AdminCustomersIdRoute
  AdminEventsIdRoute: typeof AdminEventsIdRouteWithChildren
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivitiesRoute: AdminActivitiesRoute,
  AdminCatalogRoute: AdminCatalogRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDevicesRoute: AdminDevicesRouteWithChildren,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNfcCardsRoute: AdminNfcCardsRoute,
  AdminOnlineMenuRoute: AdminOnlineMenuRoute,
  AdminOnlineOrdersRoute: AdminOnlineOrdersRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPrintQueueRoute: AdminPrintQueueRoute,
  AdminPublicLinksRoute: AdminPublicLinksRoute,
  AdminSettingsRoute: AdminSettingsRouteWithChildren,
  AdminCustomersIdRoute: AdminCustomersIdRoute,
  AdminEventsIdRoute: AdminEventsIdRouteWithChildren,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SuperAdminRouteChildren {
  SuperAdminModulesRoute: typeof SuperAdminModulesRoute
  SuperAdminOrganizationsRoute: typeof SuperAdminOrganizationsRoute
  SuperAdminPlansRoute: typeof SuperAdminPlansRoute
  SuperAdminSettingsRoute: typeof SuperAdminSettingsRoute
  SuperAdminUsersRoute: typeof SuperAdminUsersRoute
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminModulesRoute: SuperAdminModulesRoute,
  SuperAdminOrganizationsRoute: SuperAdminOrganizationsRoute,
  SuperAdminPlansRoute: SuperAdminPlansRoute,
  SuperAdminSettingsRoute: SuperAdminSettingsRoute,
  SuperAdminUsersRoute: SuperAdminUsersRoute,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  SuperAdminRoute: SuperAdminRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRoute,
  ESlugRoute: ESlugRoute,
  PSlugRoute: PSlugRoute,
  ChamadaEventoSlugRoute: ChamadaEventoSlugRoute,
  ChamadaLojaSlugRoute: ChamadaLojaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
